# Generated by Django 6.0.1 on 2026-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="priority_score",
            field=models.IntegerField(default=0),
        ),
    ]
