# Generated by Django 6.0.1 on 2026-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_engine", "0002_player_priority_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="captain_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="vice_captain_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
