# Generated by Django 6.0.1 on 2026-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_engine", "0003_team_captain_name_team_vice_captain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
