# Generated by Django 6.0.1 on 2026-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_engine", "0004_player_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.CharField(blank=True, null=True),
        ),
    ]
