# Generated by Django 6.0.1 on 2026-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_engine", "0005_alter_player_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
