# Generated by Django 6.0.1 on 2026-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_engine", "0006_alter_player_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionstate",
            name="is_unsold_round",
            field=models.BooleanField(default=False),
        ),
    ]
